language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install codecov
#
# command to run tests, e.g. python setup.py test
script:
  - py.test
  - PYTHONPATH=. coverage run test/test_escala.py

after_success:
  - codecov
