# coding=utf-8
aeroportos ={
        'AAX': 'Aeroporto de Araxá',
        'AFL': 'Aeroporto de Alta Floresta',
        'AJU': 'Aeroporto Internacional de Aracaju',
        'ARU': '',
        'ATM': 'Aeroporto de Altamira',
        'AUX': '',
        'BAZ': 'Aeroporto de Barcelos',
        'BEL': 'Aeroporto Internacional de Belém/Val de Cans',
        'BGX': 'Aeroporto Internacional Comandante Gustavo Kraemer',
        'BPS': 'Aeroporto de Porto Seguro',
        'BRA': '',
        'BSB': 'Aeroporto Internacional Presidente Juscelino Kubitschek',
        'BVB': 'Aeroporto Internacional de Boa Vista',
        'BVH': 'Aeroporto Brigadeiro Camarão',
        'BYO': '',
        'CAC': '',
        'CAW': '',
        'CCM': '',
        'CFB': '',
        'CGB': 'Aeroporto Internacional Marechal Rondon',
        'CGH': 'Aeroporto de Congonhas',
        'CGR': 'Aeroporto Internacional de Campo Grande',
        'CIZ': 'Aeroporto de Coari',
        'CKS': 'Aeroporto de Carajás',
        'CLV': '',
        'CMG': '',
        'CNF': 'Aeroporto Internacional Tancredo Neves',
        'CPV': 'Aeroporto Presidente João Suassuna',
        'CWB': 'Aeroporto Internacional Afonso Pena',
        'CXJ': '',
        'DOU': '',
        'ERN': 'Aeroporto de Eirunepé',
        'FBA': 'Aeroporto de Fonte Boa',
        'FEN': 'Aeroporto de Fernando de Noronha',
        'FLN': 'Aeroporto Internacional Hercílio Luz',
        'FOR': 'Aeroporto Internacional Pinto Martins',
        'GIG': 'Aeroporto Internacional do Rio de Janeiro',
        'GRU': 'Aeroporto Internacional de Garulhos',
        'GVR': 'Aeroporto Coronel Altino Machado',
        'GYN': 'Aeroporto Santa Genoveva',
        'HUW': 'Aeroporto de Humaiatá',
        'IGU': 'Aeroporto Internacional Cataratas',
        'IOS': 'Aeroporto_de_Ilhéus',
        'IPN': '',
        'IRZ': '',
        'ITB': 'Aeroporto de Itaituba',
        'JDF': 'Aeroporto Francisco Álvares de Assis',
        'JDO': 'Aeroporto Regional do Cariri',
        'JDR': '',
        'JOI': '',
        'JPA': '',
        'JPR': '',
        'JTC': '',
        'LBR': 'Aeroporto de Lábrea',
        'LDB': '',
        'LEC': '',
        'MAB': 'Aeroporto de Marabá',
        'MAO': 'Aeroporto Internacional Eduardo Gomes',
        'MCP': 'Aeroporto Internacional de Macapá',
        'MCZ': 'Aeroporto Internacional Zumbi dos Palmares',
        'MEA': '',
        'MGF': '',
        'MII': '',
        'MOC': 'Aeroporto de Montes Claros',
        'NAT': 'Aeroporto Internacional Augusto Severo',
        'NVT': 'Aeroporto Internacional Ministro Victor Konder',
        'OAL': '',
        'OLC': '',
        'OPS': '',
        'PET': 'Aeroporto Internacional de Pelotas',
        'PFB': '',
        'PIN': 'Aeroporto Parintins',
        'PLU': 'Aeroporto Carlos Drummond de Andrade',
        'PMW': 'Aeroporto de Palmas',
        'PNZ': '',
        'POA': 'Aeroporto Internacional Salgado Filho',
        'POJ': '',
        'PPB': '',
        'PVH': 'Aeroporto Internacional de Porto Velho',
        'QRZ': '',
        'RAO': '',
        'RBR': 'Aeroporto Internacional de Rio Branco',
        'REC': 'Aeroporto Internacional dos Guararapes Gilberto Freyre',
        'ROO': '',
        'RVD': '',
        'SDU': 'Aeroporto Santos Dumont',
        'SJK': 'Aeroporto de São José dos Campos',
        'SJL': 'Aeroporto Internacional Marechal Cunha Machado',
        'SJP': 'Aeroporto de São José do Rio Preto',
        'SLZ': '',
        'SSA': 'Aeroporto Internacional Dep. Luís Eduardo Magalhães',
        'STM': '',
        'TBT': 'Aeroporto Internacional de Tabatinga',
        'TFF': '',
        'THE': 'Aeroporto Senador Petrônio Portella',
        'TMT': 'Aeroporto de Porto Trombetas',
        'TUR': 'Aeroporto de Tucuruí',
        'UBA': '',
        'UDI': '',
        'VAG': '',
        'VCP': 'Aeroporto Internacional Viracopos',
        'VDC': '',
        'VIX': 'Aeroporto Eurico de Aguiar Salles',
        'XAP': 'Aeroporto de Chapecó',
        }

